mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpassword
    - MYSQL_DATABASE=viewsdb
    - MYSQL_RANDOM_ROOT_PASSWORD=true
#  volumes:
#    - "./conf.d:/etc/mysql/conf.d:ro"
